apiVersion: v1
kind: Service
metadata:
    name: fleetman-queue
spec:
    selector:
        app: queue    
    ports:
    - name: http
      port: 8161
      nodePort: 30090 #must be greater than 30000
      
    - name: endpoint
      port: 61616
      nodePort : 30101
      
    type: NodePort
---
apiVersion: v1
kind: Service
metadata:
    name: fleetman-position-tracker
spec:
    selector:
        app: position-tracker    
    ports:
    - name: http
      port: 8080
      nodePort : 30100
    type: NodePort #only available inside the cluster
---
apiVersion: v1
kind: Service
metadata:
    name: fleetman-api-gateway
spec:
    selector:
        app: api-gateway   
    ports:
    - name: http
      port: 8080
      nodePort: 30020 #must be greater than 30000
  
    type: NodePort 
---
apiVersion: v1
kind: Service
metadata:
    name: fleetman-webapp
spec:
    selector:
        app: webapp  
    ports:
    - name: http
      port: 80
      nodePort: 30080 #must be greater than 30000
  
    type: NodePort 


