apiVersion: v1
kind: Service
metadata:
    name: movie-info-service
spec:
    selector:
        app: movie-info        
    ports:
    - name: http
      port: 8082
      nodePort: 30082 #must be greater than 30000
    type: NodePort
---

apiVersion: v1
kind: Service
metadata:
    name: ratings-data-service
spec:
    selector:
        app: ratings-data  
    ports:
    - name: http
      port: 8083
      nodePort: 30083 #must be greater than 30000
  
    type: NodePort 
    
---

apiVersion: v1
kind: Service
metadata:
    name: movie-catalog-service
spec:
    selector:
        app: movie-catalog  
    ports:
    - name: http
      port: 8081
      nodePort: 30081 #must be greater than 30000
  
    type: NodePort 


